default:
  image: python:3.9-slim-buster
  before_script:
    - apt update
    - pip install --upgrade pip
    - pip install -e .

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install coverage pytest
    - coverage run -m pytest
    - coverage report

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx-rtd-theme sphinx-tabs
  - sphinx-build -b html docs/source public/
  artifacts:
    paths:
    - public/
  only:
  - master