image: python:3.9-slim-buster

pages:
  stage: deploy
  script:
  - apt-get update
  - pip install --upgrade pip
  - pip install -U sphinx
  - pip install sphinx-rtd-theme
  - pip install -r requirements.txt
  - sphinx-build -b html docs/source public/
  artifacts:
    paths:
    - public/
  only:
  - documentation_v2
