default:
  image: python:3.12.4-slim-bookworm
  before_script:
    - apt update
    - pip install --upgrade pip
    - pip install -e .

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install coverage pytest pytest-cov
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx-rtd-theme sphinx-tabs
  - sphinx-build -b html docs/source public/
  artifacts:
    paths:
    - public/
  only:
  - master